INSERT INTO pf_roles (name, status) VALUES
('ANONYMOUS', 'ACTIVE'),
('USER', 'ACTIVE'),
('ADMIN', 'ACTIVE');

INSERT INTO pf_animal_categories (name) VALUES
('СОБАКА'),
('КОТ'),
('РЫБКА'),
('ГРЫЗУН'),
('РЕПТИЛИЯ'),
('ПТИЦА');

INSERT INTO pf_food_types(type, code) VALUES
('Сухой', 1),
('Жидкий', 2);

INSERT INTO pf_dog_sizes(name, short_name, min_weight_kg, max_weight_kg) VALUES
('Карликовая','XS','0','2'),
('Мелкая','S','2','10'),
('Средняя','M','10','32'),
('Крупная','XL','32','99');

INSERT INTO pf_daily_food_amount (pet_category, adult_pet_size, animal_age_type, food_type, food_amount) VALUES
('собака', 'XS', 'BABY', 'сухой', 55),
('собака', 'XS', 'ADULT', 'сухой', 46),
('собака', 'XS', 'OLD', 'сухой', 70),
('собака', 'S', 'BABY', 'сухой', 112),
('собака', 'S', 'ADULT', 'сухой', 93),
('собака', 'S', 'OLD', 'сухой', 119),
('собака', 'M', 'BABY', 'сухой', 255),
('собака', 'M', 'ADULT', 'сухой', 235),
('собака', 'M', 'OLD', 'сухой', 260),
('собака', 'XL', 'BABY', 'сухой', 310),
('собака', 'XL', 'ADULT', 'сухой', 290),
('собака', 'XL', 'OLD', 'сухой', 330),
('собака', 'XS', 'BABY', 'жидкий', 45),
('собака', 'XS', 'ADULT', 'жидкий', 36),
('собака', 'XS', 'OLD', 'жидкий', 50),
('собака', 'S', 'BABY', 'жидкий', 92),
('собака', 'S', 'ADULT', 'жидкий', 73),
('собака', 'S', 'OLD', 'жидкий', 99),
('собака', 'M', 'BABY', 'жидкий', 235),
('собака', 'M', 'ADULT', 'жидкий', 216),
('собака', 'M', 'OLD', 'жидкий', 240),
('собака', 'XL', 'BABY', 'жидкий', 280),
('собака', 'XL', 'ADULT', 'жидкий', 270),
('собака', 'XL', 'OLD', 'жидкий', 290);

INSERT INTO pf_daily_food_amount (pet_category, animal_age_type, food_type, food_amount) VALUES
('кот', 'BABY', 'сухой', 35),
('кот', 'ADULT', 'сухой', 27),
('кот', 'OLD', 'сухой', 28),
('кот', 'BABY', 'жидкий', 18),
('кот', 'ADULT', 'жидкий', 15),
('кот', 'OLD', 'жидкий', 42);


INSERT INTO pf_sku_items (amount_in_package, animal_size, brand, ean_code, package_weight_kilos, pet_group, sku_name, taste, animal_category_id, food_type_id, grain_less, for_pregnant, for_castrated, for_great_fur_and_skin, for_great_bones_and_joints, for_sensitive_digestion, best_before_months, bestseller, description ) VALUES
(5, 'XS', 'Purina', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000001', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000002', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000003', 0.5, 'BABY', 'Сухой корм для собак', 'Вкус морковки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000004', 1, 'ADULT', 'Сухой корм для собак', 'Вкус ветчины', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000005', 1, 'ADULT', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000006', 1, 'ADULT', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000007', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус курицы', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000008', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус индейки', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000009', 1.5, 'OLD', 'Сухой корм для собак', 'Вкус морепродуктов', 1, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Purina', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Purina', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Purina', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Purina', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000013', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000014', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000015', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XS', 'Brit', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'S', 'Brit', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'M', 'Brit', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000001', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000002', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000003', 0.5, 'BABY', 'Жидкий корм для собак', 'Вкус морковки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000004', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус ветчины', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000005', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000006', 1, 'ADULT', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000007', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус курицы', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000008', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус индейки', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'XL', 'Brit', '0000000000009', 1.5, 'OLD', 'Жидкий корм для собак', 'Вкус морепродуктов', 1, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here');


INSERT INTO pf_sku_items (amount_in_package, brand, ean_code, package_weight_kilos, pet_group, sku_name, taste, animal_category_id, food_type_id, grain_less, for_pregnant, for_castrated, for_great_fur_and_skin, for_great_bones_and_joints, for_sensitive_digestion, best_before_months, bestseller, description ) VALUES
(5, 'Purina', '0000000000001', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000002', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус индейки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000003', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус морковки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000004', 1, 'ADULT', 'Сухой корм для котов', 'Вкус ветчины', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000005', 1, 'ADULT', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000006', 1, 'ADULT', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000007', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000008', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус индейки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000009', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус индейки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000013', 1, 'ADULT', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000014', 1, 'ADULT', 'Сухой корм для котов', 'Вкус ветчины', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000015', 1, 'ADULT', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус ветчины', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000001', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000002', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус индейки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000003', 0.5, 'BABY', 'Сухой корм для котов', 'Вкус морковки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000004', 1, 'ADULT', 'Сухой корм для котов', 'Вкус ветчины', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000005', 1, 'ADULT', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000006', 1, 'ADULT', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000007', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус курицы', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000008', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус индейки', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000009', 1.5, 'OLD', 'Сухой корм для котов', 'Вкус морепродуктов', 2, 1, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000001', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000002', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус индейки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000003', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус морковки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000004', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус ветчины', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000005', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000006', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000007', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000008', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус индейки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Purina', '0000000000009', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000010', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000011', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус индейки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000012', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000013', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000014', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус ветчины', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000015', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000016', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус ветчины', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000017', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Royal Canin', '0000000000018', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000001', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000002', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус индейки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000003', 0.5, 'BABY', 'Жидкий корм для котов', 'Вкус морковки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000004', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус ветчины', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000005', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000006', 1, 'ADULT', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000007', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус курицы', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000008', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус индейки', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here'),
(5, 'Brit', '0000000000009', 1.5, 'OLD', 'Жидкий корм для котов', 'Вкус морепродуктов', 2, 2, false,  false,  false,  false,  false,  false,  false, false, 'description here');


